apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: my-nest-app
build:
  artifacts:
    - image: my-nest-app
      context: ./
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

